SOURCES = {
    "cerebras": {
        "name": "Cerebras",
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "api_key": os.environ.get("CEREBRAS_API_KEY", ""),
        "model": "llama3.3-70b",  # CORRECTED: Current model ID
        "speed_tier": 1,
        "uncensored": False,
        "rate_limit": {"requests": 30, "window": 60},
        "daily_limit": 1000,
    },
    "groq": {
        "name": "Groq",
        "url": "https://api.groq.com/openai/v1/chat/completions",
        "api_key": os.environ.get("GROQ_API_KEY", ""),
        "model": "llama-3.3-70b-versatile",
        "speed_tier": 1,
        "uncensored": False,
        "rate_limit": {"requests": 30, "window": 60},
        "daily_limit": 14400,
    },
    "sambanova": {
        "name": "SambaNova",
        "url": "https://api.sambanova.ai/v1/chat/completions",
        "api_key": os.environ.get("SAMBANOVA_API_KEY", ""),
        "model": "Meta-Llama-3.3-70B-Instruct", # CORRECTED: Migration from deprecated model
        "speed_tier": 2,
        "uncensored": False,
        "rate_limit": {"requests": 20, "window": 60},
        "daily_limit": 5000,
    },
    "together": {
        "name": "Together",
        "url": "https://api.together.xyz/v1/chat/completions",
        "api_key": os.environ.get("TOGETHER_API_KEY", ""),
        "model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "speed_tier": 2,
        "uncensored": False,
        "rate_limit": {"requests": 10, "window": 60},
        "daily_limit": 1000,
    },
    "openrouter": {
        "name": "OpenRouter",
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "api_key": os.environ.get("OPENROUTER_API_KEY", ""),
        "model": "meta-llama/llama-3.3-70b-instruct:free",
        "speed_tier": 2,
        "uncensored": False,
        "rate_limit": {"requests": 20, "window": 60},
        "daily_limit": 5000,
    },
    "hf_abliterated": {
        "name": "HF Abliterated",
        "url": "https://router.huggingface.co/v1/chat/completions", # CORRECTED: New router endpoint
        "api_key": os.environ.get("HF_API_KEY", ""),
        "model": "mlabonne/Llama-3.1-70B-Instruct-abliterated",
        "speed_tier": 3,
        "uncensored": True,
        "rate_limit": {"requests": 5, "window": 60},
        "daily_limit": 500,
    },
    "hf_dolphin": {
        "name": "HF Dolphin",
        "url": "https://router.huggingface.co/v1/chat/completions", # CORRECTED: New router endpoint
        "api_key": os.environ.get("HF_API_KEY", ""),
        "model": "cognitivecomputations/dolphin-2.9.4-llama3.1-70b",
        "speed_tier": 3,
        "uncensored": True,
        "rate_limit": {"requests": 5, "window": 60},
        "daily_limit": 500,
    },
    "hf_hermes": {
        "name": "HF Hermes 3",
        "url": "https://router.huggingface.co/v1/chat/completions", # CORRECTED: New router endpoint
        "api_key": os.environ.get("HF_API_KEY", ""),
        "model": "NousResearch/Hermes-3-Llama-3.1-70B",
        "speed_tier": 3,
        "uncensored": True,
        "rate_limit": {"requests": 5, "window": 60},
        "daily_limit": 500,
    },
    "horde": {
        "name": "KoboldAI Horde",
        "url": "https://aihorde.net/api/v2/generate/text/async",
        "api_key": os.environ.get("HORDE_API_KEY", "0000000000"),
        "model": "",
        "speed_tier": 5,
        "uncensored": True,
        "rate_limit": {"requests": 999, "window": 60},
        "daily_limit": 999999,
    },
}
